image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r src/hide_rules/* .public
  - cp -r src/hide_rules src/param_cleaning .public/
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
